# 1. Đã sửa tên database ở cuối link thành ql_banmt
spring.datasource.url=jdbc:mysql://localhost:3306/ql_banmt?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true

# 2. Tài khoản và Mật khẩu
spring.datasource.username=root
# 3. Cấu hình chạy an toàn với DB có sẵn
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8083